name: SabineWessels
favicon: null
layout_spectrum: 0.7476751529611647
typography_spectrum: 0.6205877054017037
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.17206288571469486
  lightness: 0.37837300449609756
  saturation: 0.09797310037538409
  rhythmicContrast: 0.34860597481019795
purpose: []
