name: SabineWessels
favicon: null
layout_spectrum: 0.2254
typography_spectrum: 0.6205877054017037
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070a28'
    - '#ff585a'
    - '#ffc3e2'
    - '#00b0e0'
    - '#ff0043'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.34860597481019795
purpose: []
